Fix shellcheck warnings.

diff --git a/bin/sync-repositories b/bin/sync-repositories
--- a/bin/sync-repositories
+++ b/bin/sync-repositories
@@ -2,21 +2,11 @@
 
 function versioninfo
 {
-	VERSION="$Revision$"
-	VERSION="${VERSION%\ \$}"; VERSION="${VERSION#\:}"; VERSION="${VERSION##\ }"
-	VERSION="(CVS revision $VERSION)"
-	
-	NAME="$Name$"
-	NAME="${NAME%\ \$}"; NAME="${NAME#\:}"; NAME="${NAME##\ }"; NAME="${NAME##release-}"; NAME="${NAME//-/.}"
-	[[ -n $NAME ]] && NAME="Version $NAME "
-
-	echo ${CMDNAME}
-	echo ${NAME}${VERSION}
-
-	echo -e "\nCopyright (C) 2010 Hacking Networked Solutions"
-	echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
-	echo "This is free software: you are free to change and redistribute it."
-	echo "There is NO WARRANTY, to the extent permitted by law."
+    echo "$(basename "${0}") - version 1.0.0"
+    echo -e "\nCopyright (C) 2010-2019 Hacking Networked Solutions"
+    echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
+    echo "This is free software: you are free to change and redistribute it."
+    echo "There is NO WARRANTY, to the extent permitted by law."
 }
 
 function helpscreen
@@ -52,27 +42,42 @@ function helpscreen
     echo "      --version                  output version information and exit"
 }
 
+function die
+{
+    local msg ev
+    msg="ERROR: ${1}"
+    ev="${2}"
+    
+    if [[ -z "${ev}" ]] || (( ev < 1 )); then
+        ev=1
+    fi
+    
+    echo "${msg}" >&2
+    exit "${ev}"
+}
+
 function finish_up
 {
 	# Bzip any log files larger than 100k
 	bzip_large_logs 102400
 	
 	# If we were asked to send email send the logs to root
-	if [[ -n ${SENDEMAIL} ]]; then
+	if [[ -n "${SENDEMAIL}" ]]; then
 		send_logs_by_email "Synchronising repositories" "${ADMIN_EMAIL:-root}"
 	fi
 	
 	# If we aren't running in quiet mode show a list of the log files we generated during the update
-	if [[ -z ${QUIET} ]]; then
+	if [[ -z "${QUIET}" ]]; then
 		echo
 		display_log_paths
 	fi
 	
-	exit ${EXITSTATUS}
+	exit "${EXITSTATUS}"
 }
 
 function okorfail
 {
+    # shellcheck disable=SC2181
 	if (( ! $? )); then
 		echo "ok." 
 	else
@@ -82,13 +87,14 @@ function okorfail
 }
 
 # Init global vars
-OUTLOGLIB=/usr/lib/outlogger.sh
-CFGFILE=/etc/buildspaces
-CMDNAME=$(basename ${0})
+OUTLOGLIB="/usr/lib/outlogger.sh"
+CFGFILE="/etc/buildspaces"
+CMDNAME="$(basename "${0}")"
 EXITSTATUS=0
 
 # If the config file exists and we can read it do so.
-[[ -r ${CFGFILE} ]] && source ${CFGFILE}
+# shellcheck disable=SC1090
+[[ -r "${CFGFILE}" ]] && source "${CFGFILE}"
 
 # Process command line switches
 while (( $# > 0 ))
@@ -118,27 +124,27 @@ do
 	    -t|--sync-test)
 	    	TESTREPO=1
 			shift 1
-			while [[ (( $# > 0 )) && ${1::1} != "-" ]]
+			while [[ (( $# -gt 0 )) && ${1::1} != "-" ]]
 			do
-				[[ -z ${TESTREPOS} ]] && TESTREPOS=$1 || TESTREPOS="${TESTREPOS} $1"
+				[[ -z "${TESTREPOS}" ]] && TESTREPOS=$1 || TESTREPOS="${TESTREPOS} $1"
 				shift 1
 			done
 		;;
 	    -r|--rebuild-caches)
 	    	REBUILDCACHE=1
 			shift 1
-			while [[ (( $# > 0 )) && ${1::1} != "-" ]]
+			while [[ (( $# -gt 0 )) && ${1::1} != "-" ]]
 			do
-				[[ -z ${REBUILDREPOS} ]] && REBUILDREPOS=$1 || REBUILDREPOS="${REBUILDREPOS} $1"
+				[[ -z "${REBUILDREPOS}" ]] && REBUILDREPOS=$1 || REBUILDREPOS="${REBUILDREPOS} $1"
 				shift 1
 			done
 		;;
 	    -s|--sync-stable)
 	    	STABLEREPO=1
 			shift 1
-			while [[ (( $# > 0 )) && ${1::1} != "-" ]]
+			while [[ (( $# -gt 0 )) && ${1::1} != "-" ]]
 			do
-				[[ -z ${STABLEREPOS} ]] && STABLEREPOS=$1 || STABLEREPOS="${STABLEREPOS} $1"
+				[[ -z "${STABLEREPOS}" ]] && STABLEREPOS=$1 || STABLEREPOS="${STABLEREPOS} $1"
 				shift 1
 			done
 		;;
@@ -160,34 +166,33 @@ do
 done
 
 # If we can't read the config file we should complain and quit
-[[ ! -r ${CFGFILE} ]] && echo "ERROR: Unable to read config file at ${CFGFILE}" >&2 && exit 1 
+[[ -r ${CFGFILE} ]] || die "Unable to read config file at ${CFGFILE}" 1
 
 # Include and initialise logging library
-[[ ! -r ${OUTLOGLIB} ]] && echo "ERROR: Unable to load outlogger library from ${OUTLOGLIB}" >&2 && exit 1
-[[ -z "${LOGPATH}" ]] && echo "ERROR: No LOGPATH set in ${CFGFILE}" >&2 && exit 1
-source ${OUTLOGLIB}
-init_logging ${LOGPATH}
+[[ -r ${OUTLOGLIB} ]] || die "Unable to load outlogger library from ${OUTLOGLIB}" 1
+[[ -z "${LOGPATH}" ]] && die "No LOGPATH set in ${CFGFILE}" 1
+# shellcheck disable=SC1090
+source "${OUTLOGLIB}" 
+init_logging "${LOGPATH}"
 
 # Check configuration
-[[ -z ${REPOSROOT} ]] && echo "ERROR: No REPOSROOT set in ${CFGFILE}" >&2 && exit 1
+[[ -z ${REPOSROOT} ]] && die "No REPOSROOT set in ${CFGFILE}" 1
 if [[ -n ${LIVEREPO} ]]; then
-	[[ -z ${GENTOORSYNC} ]] && echo "ERROR: No GENTOORSYNC set in ${CFGFILE}" >&2 && exit 1
-	[[ -z ${GENTOORSOPT} ]] && echo "ERROR: No GENTOORSOPT set in ${CFGFILE}" >&2 && exit 1
+	[[ -z ${GENTOORSYNC} ]] && die "No GENTOORSYNC set in ${CFGFILE}" 1
+	[[ -z ${GENTOORSOPT} ]] && die "No GENTOORSOPT set in ${CFGFILE}" 1
 fi
 if [[ -n ${TESTREPO} || -n ${STABLEREPO} ]]; then
-	[[ -z ${BUILDSPACESXX} && -z ${BUILDSPACES32} ]] \
-		&& echo "ERROR: No BUILDSPACESXX or BUILDSPACES32 set in ${CFGFILE}" >&2 && exit 1
-	[[ -z ${TESTREPORSOPT} ]] && echo "ERROR: No TESTREPORSOPT set in ${CFGFILE}" >&2 && exit 1
-	[[ -z ${STABLEREPORSOPT} ]] && echo "ERROR: No STABLEREPORSOPT set in ${CFGFILE}" >&2 && exit 1
+	[[ -z ${BUILDSPACESXX} && -z ${BUILDSPACES32} ]] && die "No BUILDSPACESXX or BUILDSPACES32 set in ${CFGFILE}" 1
+	[[ -z ${TESTREPORSOPT} ]] && die "No TESTREPORSOPT set in ${CFGFILE}" 1
+	[[ -z ${STABLEREPORSOPT} ]] && die "No STABLEREPORSOPT set in ${CFGFILE}" 1
 fi
 
 # Check request
 [[ ${AUTOREBUILD} == "yes" && -n ${TESTREPO} && -n ${REBUILDCACHE} ]] \
-	&& echo "ERROR: AUTOREBUILD=\"yes\" set in ${CFGFILE} with --sync-test and --rebuild-caches makes no sense!" >&2 && exit 2
+	&& die "AUTOREBUILD=\"yes\" set in ${CFGFILE} with --sync-test and --rebuild-caches makes no sense!" 2
 
 # If we are not being run from a TTY then set SENDMAIL and QUIET
-tty -s
-if (( $? )); then
+if ! tty -s; then
 	SENDEMAIL=1
 	QUIET=1
 fi  
@@ -222,7 +227,7 @@ if [[ -n ${TESTREPO} ]]; then
 	# Loop through the repositories...
 	for REPO in ${TESTREPOS}; do
 		# Check that this appears to be a repository
-		if [[ ! -d ${REPOSROOT}/testing/${REPO} ]]; then
+		if [[ ! -d "${REPOSROOT}/testing/${REPO}" ]]; then
 			echo "ERROR: No repository at ${REPOSROOT}/testing/${REPO}" >&2 && exit 2
 		fi
 		[[ ! " ${BUILDSPACESXX} " =~ [[:blank:]]${REPO}[[:blank:]] && \
@@ -231,10 +236,10 @@ if [[ -n ${TESTREPO} ]]; then
 			&& echo "ERROR: ${REPO} does not appear in BUILDSPACESXX, BUILDSPACES32 or NONBUILDREPOS" >&2 && exit 2
 			 
 		# Clear the updated "flag"
-		[[ -f ${REPOSROOT}/testing/${REPO}/updated ]] && rm ${REPOSROOT}/testing/${REPO}/updated
+		[[ -f "${REPOSROOT}/testing/${REPO}/updated" ]] && rm "${REPOSROOT}/testing/${REPO}/updated"
 			 
  		# Synchronise the "live" portage tree to the testing repository 
-		[[ -n ${DONEONE} ]] && echo 
+		[[ -n "${DONEONE}" ]] && echo 
 		echo -n "Synchronising the \"live\" portage tree to the ${REPO} testing repository..."
 		exec_and_log "testing_portage_rsync_${REPO}" "rsync ${REPOSROOT}/live/portage/ ${REPOSROOT}/testing/${REPO}/portage/ ${TESTREPORSOPT}"
 		okorfail 6
@@ -242,7 +247,7 @@ if [[ -n ${TESTREPO} ]]; then
 		# If they exist then synchronise the "live" overlays to the "testing" repository
 		if [[ -d ${REPOSROOT}/live/overlays ]]; then
 			echo -n "Synchronising the \"live\" overlays to the ${REPO} testing repository..."
-			mkdir -p ${REPOSROOT}/testing/${REPO}/overlays
+			mkdir -p "${REPOSROOT}/testing/${REPO}/overlays"
 			exec_and_log "testing_overlays_rsync_${REPO}" "rsync ${REPOSROOT}/live/overlays/ ${REPOSROOT}/testing/${REPO}/overlays/${DISTOVLSUFFIX}/ ${TESTREPORSOPT}"
 			okorfail 7
 		fi
@@ -314,8 +319,8 @@ if [[ -n ${STABLEREPO} ]]; then
 			&& echo "ERROR: ${REPO} does not appear in BUILDSPACESXX, BUILDSPACES32 or NONBUILDREPOS" >&2 && exit 2
 
 		# Check that the "updated flag" is NOT set, or the --force option specified
-		[[ -n ${DONEONE} ]] && echo 
-		if [[ ! -f ${REPOSROOT}/testing/${REPO}/updated && -z ${FORCE} ]]; then
+		[[ -n "${DONEONE}" ]] && echo 
+		if [[ ! -f "${REPOSROOT}/testing/${REPO}/updated" && -z "${FORCE}" ]]; then
 			echo "The ${REPO} build-space has not been updated since the last --sync-test and --force not specified, skipping."
 		else			 
 	 		# Synchronise the "testing" configurations to the "stable" repository 
@@ -327,9 +332,9 @@ if [[ -n ${STABLEREPO} ]]; then
 			exec_and_log "stable_portage_rsync_${REPO}" "rsync ${REPOSROOT}/testing/${REPO}/portage/ ${REPOSROOT}/stable/${REPO}/portage/ ${STABLEREPORSOPT}"
 			okorfail 14
 			# If they exist synchronise the "testing" overlays to the "stable" repository
-			if [[ -d ${REPOSROOT}/testing/${REPO}/overlays ]]; then
+			if [[ -d "${REPOSROOT}/testing/${REPO}/overlays" ]]; then
 				echo -n "Synchronising the testing overlays to the ${REPO} stable repository..."
-				mkdir -p ${REPOSROOT}/stable/${REPO}/overlays
+				mkdir -p "${REPOSROOT}/stable/${REPO}/overlays"
 				exec_and_log "stable_overlays_rsync_${REPO}" "rsync ${REPOSROOT}/testing/${REPO}/overlays/ ${REPOSROOT}/stable/${REPO}/overlays/ ${STABLEREPORSOPT}"
 				okorfail 15
 			fi
diff --git a/bin/update-buildspaces b/bin/update-buildspaces
--- a/bin/update-buildspaces
+++ b/bin/update-buildspaces
@@ -2,21 +2,11 @@
 
 function versioninfo
 {
-	VERSION="$Revision$"
-	VERSION="${VERSION%\ \$}"; VERSION="${VERSION#\:}"; VERSION="${VERSION##\ }"
-	VERSION="(CVS revision $VERSION)"
-	
-	NAME="$Name$"
-	NAME="${NAME%\ \$}"; NAME="${NAME#\:}"; NAME="${NAME##\ }"; NAME="${NAME##release-}"; NAME="${NAME//-/.}"
-	[[ -n $NAME ]] && NAME="Version $NAME "
-
-	echo ${CMDNAME}
-	echo ${NAME}${VERSION}
-
-	echo -e "\nCopyright (C) 2010 Hacking Networked Solutions"
-	echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
-	echo "This is free software: you are free to change and redistribute it."
-	echo "There is NO WARRANTY, to the extent permitted by law."
+    echo "$(basename "${0}") - version 1.0.0"
+    echo -e "\nCopyright (C) 2010-2019 Hacking Networked Solutions"
+    echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
+    echo "This is free software: you are free to change and redistribute it."
+    echo "There is NO WARRANTY, to the extent permitted by law."
 }
 
 function helpscreen
@@ -40,14 +30,31 @@ function helpscreen
     echo "      --version                  output version information and exit"
 }
 
+function die
+{
+    local msg ev
+    msg="ERROR: ${1}"
+    ev="${2}"
+    
+    if [[ -z "${ev}" ]] || (( ev < 1 )); then
+        ev=1
+    fi
+    
+    echo "${msg}" >&2
+    exit "${ev}"
+}
+
 # Init global vars
-CFGFILE=/etc/buildspaces
-CMDNAME=$(basename ${0})
+BUILDSPACESXX=""
+BUILDSPACES32=""
+CFGFILE="/etc/buildspaces"
+CMDNAME="$(basename "${0}")"
 EXITSTATUS=0
 UPDATE_FLAGS=""
 
 # If we can read the config file do so
-[[ -r ${CFGFILE} ]] && source ${CFGFILE}
+# shellcheck disable=SC1090
+[[ -r "${CFGFILE}" ]] && source "${CFGFILE}"
 
 # Process command line switches
 while (( $# > 0 ))
@@ -73,27 +80,26 @@ do
 			versioninfo
 			exit
 		;;	
-		-*|--*)
+		-*)
 			helpscreen
 			exit
 		;;
 		
 		*)
 			# Add this build-space to the list of build-spaces
-			[[ -z ${BUILDSPACES} ]] && BUILDSPACES=$1 || BUILDSPACES="${BUILDSPACES} $1"
+			[[ -z "${BUILDSPACES}" ]] && BUILDSPACES="$1" || BUILDSPACES="${BUILDSPACES} $1"
 		;;
 	esac
 	shift 1
 done
 
 # If we can't read the config file complain and quit
-[[ ! -r ${CFGFILE} ]] && echo "ERROR: Unable to read config file at ${CFGFILE}" >&2 && exit 1 
+[[ -r "${CFGFILE}" ]] && die "Unable to read config file at ${CFGFILE}" 1 
 
 # Check configuration
-[[ -z ${REPOSROOT} ]] && echo "ERROR: No REPOSROOT set in ${CFGFILE}" >&2 && exit 2
-[[ -z ${BUILDSPACEROOT} ]] && echo "ERROR: No BUILDSPACEROOT set in ${CFGFILE}" >&2 && exit 2
-[[ -z ${BUILDSPACESXX} && -z ${BUILDSPACES32} ]] \
-	 && echo "ERROR: No BUILDSPACESXX or BUILDSPACES32 set in ${CFGFILE}" >&2 && exit 2
+[[ -z "${REPOSROOT}" ]] && die "No REPOSROOT set in ${CFGFILE}" 2
+[[ -z "${BUILDSPACEROOT}" ]] && die "No BUILDSPACEROOT set in ${CFGFILE}" 2
+[[ -z "${BUILDSPACESXX}" && -z "${BUILDSPACES32}" ]] && die "No BUILDSPACESXX or BUILDSPACES32 set in ${CFGFILE}" 2
 
 # If we have been asked to update all build-spaces make a list
 [[ ${BUILDSPACES} = "all" ]] && BUILDSPACES="${BUILDSPACESXX} ${BUILDSPACES32}"
@@ -103,25 +109,25 @@ for BUILDSPACE in ${BUILDSPACES}; do
 	# Check that this appears to be a build-space
 	[[ ! " ${BUILDSPACESXX} " =~ [[:blank:]]${BUILDSPACE}[[:blank:]] && \
 	   ! " ${BUILDSPACES32} " =~ [[:blank:]]${BUILDSPACE}[[:blank:]] ]] \
-		&& echo "ERROR: ${BUILDSPACE} does not appear in BUILDSPACESXX or BUILDSPACES32" >&2 && exit 2
-	[[ ! -d ${BUILDSPACEROOT}/${BUILDSPACE} ]] && \
-		echo "ERROR: No build-space at ${BUILDSPACEROOT}/${BUILDSPACE}" >&2 && exit 2
+		&& die "${BUILDSPACE} does not appear in BUILDSPACESXX or BUILDSPACES32" 2
+	[[ -d "${BUILDSPACEROOT}/${BUILDSPACE}" ]] || die "No build-space at ${BUILDSPACEROOT}/${BUILDSPACE}" 2
 
 	# If the build-space is on the same architecture as the host run update-buildspace
 	# otherwise run linux32 update-buildspace
 	if [[ " ${BUILDSPACESXX} " =~ [[:blank:]]${BUILDSPACE}[[:blank:]] ]]; then
 		# If the build-space has already been successfully updated since the last sync
 		# and the --force flag has not been used then display a warning and skip it.
-		if [[ -f ${REPOSROOT}/testing/${BUILDSPACE}/updated && -z ${FORCE} ]]; then
+		if [[ -f "${REPOSROOT}/testing/${BUILDSPACE}/updated" && -z "${FORCE}" ]]; then
 			echo "Skipping the [native] ${BUILDSPACE} build-space...already updated."
 		else
 			echo -n "Updating the [native] ${BUILDSPACE} build-space..."
-			if [[ -z ${PRETEND} ]]; then
-				chroot ${BUILDSPACEROOT}/${BUILDSPACE} /usr/bin/update-buildspace --quiet ${UPDATE_FLAGS}
-				if (( ! $? )); then
+			if [[ -z "${PRETEND}" ]]; then
+                # We want ${UPDATE_FLAGS} to split
+                # shellcheck disable=SC2086
+				if chroot "${BUILDSPACEROOT}/${BUILDSPACE}" /usr/bin/update-buildspace --quiet ${UPDATE_FLAGS}; then
 					echo "ok." 
 					# Set the updated "flag"
-					touch ${REPOSROOT}/testing/${BUILDSPACE}/updated
+					touch "${REPOSROOT}/testing/${BUILDSPACE}/updated"
 				else
 					echo "failed."
 					EXITSTATUS=3
@@ -133,16 +139,17 @@ for BUILDSPACE in ${BUILDSPACES}; do
 	else
 		# If the build-space has already been successfully updated since the last sync
 		# and the --force flag has not been used then display a warning and skip it.
-		if [[ -f ${REPOSROOT}/testing/${BUILDSPACE}/updated && -z ${FORCE} ]]; then
+		if [[ -f "${REPOSROOT}/testing/${BUILDSPACE}/updated" && -z "${FORCE}" ]]; then
 			echo "Skipping the [32-bit] ${BUILDSPACE} build-space...already updated."
 		else
 			echo -n "Updating the [32-bit] ${BUILDSPACE} build-space..."
-			if [[ -z ${PRETEND} ]]; then
-				linux32 chroot ${BUILDSPACEROOT}/${BUILDSPACE} /usr/bin/update-buildspace --quiet ${UPDATE_FLAGS}
-				if (( ! $? )); then
+			if [[ -z "${PRETEND}" ]]; then
+			    # We want ${UPDATE_FLAGS} to split
+			    # shellcheck disable=SC2086
+				if linux32 chroot "${BUILDSPACEROOT}/${BUILDSPACE}" /usr/bin/update-buildspace --quiet ${UPDATE_FLAGS}; then
 					echo "ok." 
 					# Set the updated "flag"
-					touch ${REPOSROOT}/testing/${BUILDSPACE}/updated
+					touch "${REPOSROOT}/testing/${BUILDSPACE}/updated"
 				else
 					echo "failed."
 					EXITSTATUS=3
