Improved error checking and handling in _outcatcher.sh. Modified all scripts to use /etc/buildspace as config. Switched to common help-screen handling and option parsing. Added log writable check to delete-redundant-libs. Modified do-update to use LOGPATH from config file for log. Removed unnecessary source /etc/profile calls. Minor error handling fixes to free-distfiles-space. Updated sync-portage-testing.sh to use new version of update-portage-metadata. Removed old update-portage-metadata.sh script. Added new update-portage-metadata script.

diff --git a/src/delete-redundant-libs b/src/delete-redundant-libs
--- a/src/delete-redundant-libs
+++ b/src/delete-redundant-libs
@@ -2,8 +2,7 @@
 
 function helpscreen
 {
-	NAME=$(basename ${0})
-	echo "Usage: ${NAME} [OPTION]..."
+	echo "Usage: ${CMDNAME} [OPTION]..."
 	echo "Runs revdep-rebuild --library for libraries requiring it and deletes any"
 	echo "libraries which are no longer required once the rebuild is complete"
 	echo
@@ -15,13 +14,15 @@ function helpscreen
 }
 
 # Init local vars
-CFGFILE=/etc/buildserver
+CFGFILE=/etc/buildspace
+CMDNAME=$(basename ${0})
 
 # If the config file exists and we can read it do so
-[[ -r ${CFGFILE} ]] && source ${CFGFILE}
+[[ ! -r ${CFGFILE} ]] && echo "Error: No config file (or no read permissions) at ${CFGFILE}" >&2 && exit 2
+source ${CFGFILE}
 
 # Process command line switches
-while [ $# -gt 0 ]
+while (( $# > 0 ))
 do
 	case $1 in
 		-l|--log-path)
@@ -41,25 +42,14 @@ do
 	esac
 done
 
-# Check to make sure we are being run from inside the buildspace.
-if [ -z "$BUILDSPACE_NAME" ]; then
-	echo "ERROR: $0 should only be run from inside a buildspace!" >&2
-	exit 1
-fi
-
 # Check config
-if [[ -z ${LOGPATH} ]]; then
-	if [[ ! -r ${CFGFILE} ]]; then
-		echo "Error: No config file (or no read permissions) at ${CFGFILE} and not all required options were specified" 1>&2
-		exit 2
-	fi
-	echo "Error: You have no LOGPATH set in ${CFGFILE} and none was specified" 1>&2
-	exit 2
-fi	
+[[ -z ${BUILDSPACE_NAME} ]] && echo "ERROR: ${CMDNAME} should only be run inside a configured buildspace!" >&2 && exit 2
+[[ -z ${LOGPATH} ]] && echo "ERROR: You have no LOGPATH set in ${CFGFILE} and none was specified" >&2 && exit 2
 
 # Path to the build log.
 BLP="${LOGPATH}/build_phase.out.log"
-[[ ! -r ${BLP} ]] && echo "Error: Unable to read build phase log file at ${BLP}" 1>&2 && exit 3
+[[ ! -r ${BLP} ]] && echo "ERROR: Unable to read build phase log file at ${BLP}" >&2 && exit 3
+[[ ! -w ${LOGPATH} ]] && echo "ERROR: No write permissions on ${LOGPATH}" >&2 && exit 3
 
 # Search the build log and display any libraries for which a revdep-rebuild is suggested.
 echo "Libraries needing revdep-rebuild:"
diff --git a/src/do-update b/src/do-update
--- a/src/do-update
+++ b/src/do-update
@@ -5,7 +5,8 @@ env-update --no-ldconfig &>/dev/null
 source /etc/profile &>/dev/null
 
 # Init local vars
-CFGFILE=/etc/buildserver
+CFGFILE=/etc/buildspace
+CMDNAME=$(basename ${0})
 
 # If the config file exists and we can read it do so
 [[ ! -r ${CFGFILE} ]] && echo "ERROR: Unable to read config file at ${CFGFILE}" >&2 && exit 1 
@@ -16,7 +17,7 @@ source _outcatcher.sh
 init_logging ${LOGPATH}
 
 # Check to make sure we are being run from inside the buildspace.
-[[ -z "$BUILDSPACE_NAME" ]] && echo "ERROR: $0 should only be run from inside a buildspace!" >&2 && exit 1
+[[ -z "${BUILDSPACE_NAME}" ]] && echo "ERROR: ${CMDNAME} should only be run inside a configured buildspace!" >&2 && exit 1
 
 # Clean the portage and binary package temporary directories
 PTD=$(portageq envvar PORTAGE_TMPDIR)
@@ -29,9 +30,9 @@ rm -rf ${PTD}/binpkgs/*
 # If we are not being run from a TTY then redirect output to ~/update.out
 tty -s
 tty=$?
-[[ $tty -gt 0 ]] && exec 1> ~/update.out.log
+[[ $tty -gt 0 ]] && exec 1> ${LOGPATH}/update.out.log
 
-echo -e "Starting automated update of [$BUILDSPACE_NAME] buildspace.\n"
+echo -e "Starting automated update of [${BUILDSPACE_NAME}] buildspace.\n"
 
 # Ensure free space is available for distfiles
 free-distfiles-space --free-delete
@@ -208,7 +209,7 @@ else
 		echo
 	fi 
 	 
-	echo -e "\nAutomated update of [$BUILDSPACE_NAME] buildspace completed.\n"
+	echo -e "\nAutomated update of [${BUILDSPACE_NAME}] buildspace completed.\n"
 fi
 
 # Bzip any log files larger than 100k
@@ -218,9 +219,9 @@ bzip_large_logs 102400
 # end the redirect of 1&2 otherwise display summary message.
 get_log_files logfiles
 if [[ $tty -gt 0 ]]; then
-	mutt -s "Automated update of $BUILDSPACE_NAME" \
+	mutt -s "Automated update of ${BUILDSPACE_NAME}" \
          -a ${logfiles} \
-         -- root < ~/update.out.log
+         -- root < ${LOGPATH}/update.out.log
   	exec 1>&1
 	(( ! $? )) && clean_up_logs
 else
diff --git a/src/free-distfiles-space b/src/free-distfiles-space
--- a/src/free-distfiles-space
+++ b/src/free-distfiles-space
@@ -17,7 +17,7 @@ function helpscreen
 }
 
 # Process command line switches
-while [[ $# -gt 0 ]]
+while (( $# > 0 ))
 do
 	case $1 in
 		-d|--free-delete)
@@ -43,22 +43,14 @@ do
 	esac
 done
 
-# Source the profile (we're probably being run in a chroot and this may not have been done)
-source /etc/profile &>/dev/null
-
-# Check to make sure we are being run from inside the buildspace.
-if [ -z "$BUILDSPACE_NAME" ]; then
-	echo "ERROR: $0 should only be run from inside a buildspace!" >&2
-	exit 2
-fi
-
 # Get the location of the DISTDIR
 DISTDIR=$(portageq distdir)
+[[ -z ${DISTDIR} || (( ! $? )) ]] &&  echo "ERROR: Unable to locate DISTDIR" >&2 && exit 2
 
 # If we have been asked to display current free space then...
 if [[ -n ${DISPLAYFREE} ]]; then
 	FREEBYTES=$(df -P -B 1 ${DISTDIR} 2>/dev/null | tail -1 | awk '{print $4}')
-	[[ $? ]] || ( echo "Unable to calculate free disk space in DISTDIR (${DISTDIR})" && exit 1 )
+	(( $? )) && echo "Unable to calculate free disk space in DISTDIR (${DISTDIR})" >&2 && exit 1
 	FREESPACE=$(( ${FREEBYTES} / 1024 )) UNITS="KB"
 	(( ${FREESPACE} > 1024 )) && FREESPACE=$(( ${FREESPACE} / 1024 )) UNITS="MB"
 	(( ${FREESPACE} > 1024 )) && FREESPACE=$(( ${FREESPACE} / 1024 )) UNITS="GB"
diff --git a/src/merge-new-configs b/src/merge-new-configs
--- a/src/merge-new-configs
+++ b/src/merge-new-configs
@@ -2,8 +2,7 @@
 
 function helpscreen
 {
-	NAME=$(basename ${0})
-	echo "Usage: ${NAME} [OPTION]..."
+	echo "Usage: ${CMDNAME} [OPTION]..."
 	echo "Automatically deletes updated configuration files for those files listed"
 	echo "then unconditionally merges remaining configuration files"
 	echo
@@ -12,17 +11,15 @@ function helpscreen
 }
 
 # Init local vars
-CFGFILE=/etc/merge-new-configs
-
-# If the config file exists and we can read it do so
-[[ -r ${CFGFILE} ]] && source ${CFGFILE}
+CFGFILE=/etc/buildspace
+CMDNAME=$(basename ${0})
 
 # Process command line switches
 while [[ $# -gt 0 ]]
 do
 	case $1 in
 		-f|--files)
-			FILES=$2
+			CONFFILES=$2
 			shift 2
 	    ;;
 				
@@ -34,29 +31,17 @@ do
 	esac
 done
 
-# Source the profile
-source /etc/profile &>/dev/null
-
-# Check to make sure we are being run from inside the buildspace.
-if [[ -z "$BUILDSPACE_NAME" ]]; then
-	echo "ERROR: $0 should only be run from inside a buildspace!" >&2
-	exit 1
-fi
+# If the config file exists and we can read it do so
+[[ ! -r ${CFGFILE} && -z ${CONFFILES} ]] && echo "Error: No config file (or no read permissions) at ${CFGFILE}" >&2 && exit 2
+source ${CFGFILE}
 
 # Check config
-if [[ -z ${FILES} ]]; then
-	if [[ ! -r ${CFGFILE} ]]; then
-		echo "Error: No config file (or no read permissions) at ${CFGFILE} and not all required options were specified"
-		exit 2
-	fi
-	echo "Error: You have no FILES set in ${CFGFILE} and none were specified" 1>&2
-	exit 2
-fi	
+[[ -z ${CONFFILES} ]] && echo "Error: You have no CONFFILES set in ${CFGFILE} and none were specified" >&2 && exit 2	
 
 # Loop through the files above searching for any configuration files which
 # match.  If any are found for that file display them and delete them.
 echo "Searching for new configurations for:"
-for F in ${FILES}; do
+for F in ${CONFFILES}; do
 	echo -n "    ${F} : "
 	FTD=$(find /etc -name "._cfg*${F}*" | xargs -r)
 	if [[ -z ${FTD} ]]; then
diff --git a/src/remerge-missing-binaries b/src/remerge-missing-binaries
--- a/src/remerge-missing-binaries
+++ b/src/remerge-missing-binaries
@@ -2,8 +2,7 @@
 
 function helpscreen
 {
-	NAME=$(basename ${0})
-	echo "Usage: ${NAME} [OPTION]..."
+	echo "Usage: ${CMDNAME} [OPTION]..."
 	echo "Reinstalls any packages which are installed but which do not have a"
 	echo "corresponding binary package available"
 	echo
@@ -14,10 +13,17 @@ function helpscreen
 	echo "                                 rebuilt"
 }
 
+# Init local vars
+CFGFILE=/etc/buildspace
+CMDNAME=$(basename ${0})
 DEPS="--with-bdeps n"
 
+# If the config file exists and we can read it do so
+[[ ! -r ${CFGFILE} ]] && echo "Error: No config file (or no read permissions) at ${CFGFILE}" >&2 && exit 2
+source ${CFGFILE}
+
 # Process command line switches
-while [[ $# -gt 0 ]]
+while (( $# > 0 ))
 do
 	case $1 in
 	    -b|--include-bdeps)
@@ -37,14 +43,8 @@ do
 	esac
 done
 
-# Source the profile
-source /etc/profile &>/dev/null
-
 # Check to make sure we are being run from inside the buildspace.
-if [ -z "$BUILDSPACE_NAME" ]; then
-	echo "ERROR: $0 should only be run from inside a buildspace!" >&2
-	exit 1
-fi
+[[ -z "${BUILDSPACE_NAME}" ]] && echo "ERROR: ${CMDNAME} should only be run inside a configured buildspace!" >&2 && exit 1
 
 # Remerge forgotten binaries!
 emerge -pvek world ${DEPS} 2>&1 1>&1 | \
