Updated to-do list. Added functionality to rebuild binary packages containing preserved libraries to delete-redundant-libs. Modified revdep-rebuild section of do-update to perform a second (pretend and if needed full) pass whenever a first pass rebuild is required.

diff --git a/src/delete-redundant-libs b/src/delete-redundant-libs
--- a/src/delete-redundant-libs
+++ b/src/delete-redundant-libs
@@ -79,8 +79,18 @@ DELETELIBS=$(awk '/# rm/ { x=1; do { x++; } while ($(x-1) != "rm") print $x }' <
 if [[ -z ${DELETELIBS} ]]; then
 	echo "    none"
 else
+	PKGLIST=" "
 	for L in ${DELETELIBS}; do
-		echo "    ${L}"
+		if [[ -e ${L} ]]; then
+			echo "    ${L} - "
+			OWNINGPKG=$(qfile -v -C ${L} | cut -f 1 -d " ")
+			if [[ -n ${OWNINGPKG} ]]; then
+				echo "owned by ${OWNINGPKG}"
+				[[ "${PKGLIST}" =~ [[:blank:]]${OWNINGPKG}[[:blank:]] ]] || PKGLIST="${PKGLIST}${OWNINGPKG} "
+			else
+				echo "unclaimed"
+			fi
+		fi
 	done
 fi
 
@@ -93,18 +103,30 @@ if [[ -n ${REBUILDLIBS} ]]; then
 	for L in ${REBUILDLIBS}; do
 		echo -n "    ${L} "
 		revdep-rebuild --no-progress --library ${L} \
-			1>${LOGPATH}/delete_redundant_libs.${L}.aux.out.log 2>${LOGPATH}/delete_redundant_libs.${L}.aux.err.log
+			1>${LOGPATH}/delete_redundant_libs.rr.${L}.aux.out.log 2>${LOGPATH}/delete_redundant_libs.rr.${L}.aux.err.log
 		(( ! $? )) && echo " - ok" || echo " - failed"
 	done
 fi
 
-# Search the build log and delete any libraries which can be safely removed.
+# Delete any libraries which are no longer needed
 if [[ -n ${DELETELIBS} ]]; then
 	echo -e "\nDeleting old libraries:"  
 	for L in ${DELETELIBS}; do
-		echo "    ${L}"
-		rm ${L}
+		if [[ -e ${L} ]]; then
+			echo -n "    ${L}"
+			rm ${L}
+			(( ! $? )) && echo " - ok" || echo " - failed"
+		fi
+	done
+fi
+
+# Rebuild any binary packages containing above libraries
+if [[ -n ${PKGLIST} && ${PKGLIST} != " " ]]; then 
+	echo -e "\nRebuilding binary packages containing preserved libraries:"
+	for PKG in ${PKGLIST}; do
+		echo -n "    ${PKG} "
+		emerge -1 =${PKG} \
+			1>${LOGPATH}/delete_redundant_libs.rm.${L}.aux.out.log 2>${LOGPATH}/delete_redundant_libs.rm.${L}.aux.err.log
 		(( ! $? )) && echo " - ok" || echo " - failed"
 	done
 fi
-	
diff --git a/src/do-update b/src/do-update
--- a/src/do-update
+++ b/src/do-update
@@ -126,18 +126,20 @@ else
 	(( ! $? )) && echo "done." || echo "failed."
 	
 	# Rebuild broken binaries
-	echo -n "Rebuilding broken binaries (pretend)..."
-	exec_and_log revdep_rebuild_p0 "revdep-rebuild -i -p -P"
+	echo -n "Rebuilding broken binaries (pass 1 - pretend)..."
+	exec_and_log revdep_rebuild_1_pretend "revdep-rebuild -i -p -P"
 	(( ! $? )) && echo "done." || echo "failed."
 	if [[ -e /var/cache/revdep-rebuild/3_broken.rr ]]; then
-		echo -n "Rebuilding broken binaries (pass 1)..."
-		exec_and_log revdep_rebuild_p1 "revdep-rebuild -P -- --keep-going"
-		if (( ! $? )); then
-			echo "done."
-		else
-			echo "failed."
-			echo -n "Rebuilding broken binaries (pass 2)..."
-			exec_and_log revdep_rebuild_p2 "revdep-rebuild -P -- --keep-going"
+		echo -n "Rebuilding broken binaries (pass 1 - remerge)..."
+		exec_and_log revdep_rebuild_1_remerge "revdep-rebuild -P -- --keep-going"
+		(( ! $? )) && echo "done." || echo "failed."
+		
+		echo -n "Rebuilding broken binaries (pass 2 - pretend)..."
+		exec_and_log revdep_rebuild_2_pretend "revdep-rebuild -i -p -P"
+		(( ! $? )) && echo "done." || echo "failed."
+		if [[ -e /var/cache/revdep-rebuild/3_broken.rr ]]; then
+			echo -n "Rebuilding broken binaries (pass 2 - remerge)..."
+			exec_and_log revdep_rebuild_2_remerge "revdep-rebuild -P -- --keep-going"
 			(( ! $? )) && echo "done." || echo "failed."
 		fi
 	fi
