Minor fixes.

diff --git a/src/free-distfiles-space b/src/free-distfiles-space
--- a/src/free-distfiles-space
+++ b/src/free-distfiles-space
@@ -47,8 +47,8 @@ source /etc/profile &>/dev/null
 
 # Check to make sure we are being run from inside the buildspace.
 if [ -z "$BUILDSPACE_NAME" ]; then
-  echo "ERROR: $0 should only be run from inside a buildspace!" >&2
-  exit 2
+	echo "ERROR: $0 should only be run from inside a buildspace!" >&2
+	exit 2
 fi
 
 # Get the location of the DISTDIR
@@ -56,11 +56,11 @@ DISTDIR=$(portageq distdir)
 
 # If we have been asked to display current free space then...
 if [[ -n ${DISPLAYFREE} ]]; then
-	FREEBYTES=$(df -B 1 ${DISTDIR} 2>/dev/null | tail -1 | awk '{print $4}')
+	FREEBYTES=$(df -P -B 1 ${DISTDIR} 2>/dev/null | tail -1 | awk '{print $4}')
 	[[ $? ]] || ( echo "Unable to calculate free disk space in DISTDIR (${DISTDIR})" && exit 1 )
-	( FREESPACE=$(( ${FREEBYTES} / 1024 )) UNITS="KB" )
-	(( ${FREESPACE} \> 1024 )) && ( FREESPACE=$(( ${FREESPACE} / 1024 )) UNITS="MB" )
-	(( ${FREESPACE} \> 1024 )) && ( FREESPACE=$(( ${FREESPACE} / 1024 )) UNITS="GB" )
+	FREESPACE=$(( ${FREEBYTES} / 1024 )) UNITS="KB"
+	(( ${FREESPACE} > 1024 )) && FREESPACE=$(( ${FREESPACE} / 1024 )) UNITS="MB"
+	(( ${FREESPACE} > 1024 )) && FREESPACE=$(( ${FREESPACE} / 1024 )) UNITS="GB"
 	echo "Free space available in DISTDIR (${DISTDIR}) : ${FREESPACE} ${UNITS} (${FREEBYTES} bytes)"
 fi
 
@@ -89,9 +89,9 @@ if [[ -n ${GETREQUIRED} || -n ${DISPLAYREQUIRED} ]]; then
 	# Calculate in bytes
 	shopt -s nocasematch
 	case "$units" in
-	  "kb") REQSIZE=$(( ${REQSIZE} * 1024 )) ;;
-	  "mb") REQSIZE=$(( ${REQSIZE} * 1024 * 1024 )) ;;
-	  "gb") REQSIZE=$(( ${REQSIZE} * 1024 * 1024 * 1024 )) ;;
+		"kb") REQSIZE=$(( ${REQSIZE} * 1024 )) ;;
+		"mb") REQSIZE=$(( ${REQSIZE} * 1024 * 1024 )) ;;
+		"gb") REQSIZE=$(( ${REQSIZE} * 1024 * 1024 * 1024 )) ;;
 	esac
 	shopt -u nocasematch
 	
