Minor improvements.

diff --git a/src/free-distfiles-space b/src/free-distfiles-space
--- a/src/free-distfiles-space
+++ b/src/free-distfiles-space
@@ -56,65 +56,61 @@ DISTDIR=$(portageq distdir)
 
 # If we have been asked to display current free space then...
 if [[ -n ${DISPLAYFREE} ]]; then
-	FREESPACE=$(df -h ${DISTDIR} 2>/dev/null | tail -1 | awk '{print $4}')
-	[[ $? ]] || ( echo "Unable to calculate free disk space in DISTDIR (${DISTDIR})" && exit 1 ) 
-	echo "Free space available in DISTDIR (${DISTDIR}) : ${FREESPACE}B"
+	FREEBYTES=$(df -B 1 ${DISTDIR} 2>/dev/null | tail -1 | awk '{print $4}')
+	[[ $? ]] || ( echo "Unable to calculate free disk space in DISTDIR (${DISTDIR})" && exit 1 )
+	( FREESPACE=$(( ${FREEBYTES} / 1024 )) UNITS="KB" )
+	(( ${FREESPACE} > 1024 )) && ( FREESPACE=$(( ${FREESPACE} / 1024 )) UNITS="MB" )
+	(( ${FREESPACE} > 1024 )) && ( FREESPACE=$(( ${FREESPACE} / 1024 )) UNITS="GB" )
+	echo "Free space available in DISTDIR (${DISTDIR}) : ${FREESPACE} ${UNITS} (${FREEBYTES} bytes)"
 fi
 
 
 # If we have been asked to display required free space then...
 if [[ -n ${GETREQUIRED} || -n ${DISPLAYREQUIRED} ]]; then
 	# Get size of downloads for this update
-	# Eg: sizeStr="Total: 3 packages (3 upgrades), Size of downloads: 1,497 kB"
-	sizeStr=$(emerge -pvuDN world | grep "Size of downloads:")
+	# Eg: SIZESTR="Total: 3 packages (3 upgrades), Size of downloads: 1,497 kB"
+	SIZESTR=$(emerge -pvuDN world | grep "Size of downloads:")
 	
-	# Split result string
+	# SPLIT result string
 	oIFS=$IFS
-	IFS=':' split1=($sizeStr)
-	IFS=' ' split2=(${split1[2]})
+	IFS=':' SPLIT1=(${SIZESTR})
+	IFS=' ' SPLIT2=(${SPLIT1[2]})
 	IFS=$oIFS
 	
 	# Get size and units
-	reqSize=${split2[0]//,/}
-	units=${split2[1]}
-	
-	# If size is 0 then we're done
-	if [ $(($reqSize)) == 0 ]; then
-	  [[ -n ${DISPLAYREQUIRED} ]] && echo 0
-	  exit
-	fi
+	REQSIZE=${SPLIT2[0]//,/}
+	units=${SPLIT2[1]}
 	
 	# Add 10%
-	reqSize=$(( $reqSize + ${reqSize:0:$(( ${#reqSize} - 1 ))} ))
+	REQSIZE=$(( ${REQSIZE} + ${REQSIZE} / 10 ))
 
-	[[ -n ${DISPLAYREQUIRED} ]] && echo -n "Free space required in DISTDIR (${DISTDIR}) : ${reqSize} ${units}"
+	[[ -n ${DISPLAYREQUIRED} ]] && echo -n "Free space required in DISTDIR (${DISTDIR}) : ${REQSIZE} ${units}"
 	
 	# Calculate in bytes
 	shopt -s nocasematch
 	case "$units" in
-	  "kb") reqSize=$(( $reqSize * 1024 )) ;;
-	  "mb") reqSize=$(( $reqSize * 1024 * 1024 )) ;;
-	  "gb") reqSize=$(( $reqSize * 1024 * 1024 * 1024 )) ;;
+	  "kb") REQSIZE=$(( ${REQSIZE} * 1024 )) ;;
+	  "mb") REQSIZE=$(( ${REQSIZE} * 1024 * 1024 )) ;;
+	  "gb") REQSIZE=$(( ${REQSIZE} * 1024 * 1024 * 1024 )) ;;
 	esac
 	shopt -u nocasematch
 	
 	# Display result
-	[[ -n ${DISPLAYREQUIRED} ]] && echo " ($(( 0 + reqSize )) bytes)"
+	[[ -n ${DISPLAYREQUIRED} ]] && echo " (${REQSIZE}) bytes)"
 fi
 
 
 # If we have been asked to free the required space then...
 if [[ -n ${FREEDELETE} ]]; then
-	# Store current directory, repeatedly delete oldest 20 files from distfiles
+	# Store current directory, repeatedly delete oldest 10 files from distfiles
 	# directory until there is sufficient free space, restore current directory.
 	pushd ${DISTDIR} > /dev/null 
-	
-	if [[ `df . -P -B 1 2>/dev/null | tail -1 | awk '{print $4}'` -gt $(($reqSize)) ]]; then
-		exit
-	fi
+
+	# We may be done already, if so quit	
+	(( $(df . -P -B 1 2>/dev/null | tail -1 | awk '{print $4}') -ge ${REQSIZE} )) && exit
 	
 	echo -n "Freeing space for distfiles..."
-	while [[ `df . -P -B 1 2>/dev/null | tail -1 | awk '{print $4}'` -lt $(($reqSize)) ]] 
+	while (( $(df . -P -B 1 2>/dev/null | tail -1 | awk '{print $4}') -lt ${REQSIZE} ))
 	do 
 	  	rm `ls -1 --time=atime --sort=time --reverse | head --lines=20` 
 	  	echo -n "."
